spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:h2:mem:courses
    username: courses
    password: courses123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret-key: d2ViNC1ub3Qtc28tc2VjcmV0LWFjY2Vzcy1zZWNyZXQ=

cors:
  allowed-origins:
    - "http://localhost:3000"
