spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 3000
cors:
  allowed-origins:
    - http://localhost:8080
