spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://projectv2-postgres.postgres.database.azure.com:5432/courses?currentSchema=courses&ssl=require
    driver-class-name: org.postgresql.Driver
    username: tomasvaneynde
    password: Panda3212
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret-key: d2ViNC1ub3Qtc28tc2VjcmV0LWFjY2Vzcy1zZWNyZXQ=
