spring:
  application:
    name: courses
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: true
    open-in-view: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          authority-prefix: ""